# Generated by Django 5.1.6 on 2025-03-31 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0038_eventextralink"),
        ("submission", "0077_answeroption_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="LlmModels",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("comment", models.TextField(default="")),
                ("active", models.BooleanField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "name"), name="unique_provider_event"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LlmEventModels",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pretalx_llm.llmmodels",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LlmEmbedding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(null=True)),
                ("embedding", models.JSONField(null=True)),
                ("task_id", models.CharField(max_length=50)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submission.submission",
                    ),
                ),
                (
                    "event_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pretalx_llm.llmeventmodels",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_model", "submission", "title", "description"),
                        name="unique_event_submission_model",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="llmeventmodels",
            constraint=models.UniqueConstraint(
                fields=("name", "event"), name="unique_event_model"
            ),
        ),
    ]
