# Generated by Django 5.1.8 on 2025-04-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretalx_llm", "0002_llmuserpreference_llmuserpreferenceembedding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmembedding",
            name="abstract",
            field=models.TextField(null=True),
        ),
    ]
