# Generated by Django 5.1.8 on 2025-04-21 11:10

from django.db import migrations


def delete_old_embeddings(apps, schema_editor):
    """
    _Delete all embeddings in the database_

    Previously, embeddings were based on the title and description. The previous (0003_llmembedding_abstract) migration adds the abstract as well. This migration deletes all existing embeddings in the database. They will be automatically regenerated using the new method that uses the abstract as well.
    """
    embeddings = apps.get_model("pretalx_llm", "LlmEmbedding")
    embeddings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("pretalx_llm", "0003_llmembedding_abstract"),
    ]

    operations = [
        migrations.RunPython(delete_old_embeddings, reverse_code=delete_old_embeddings)
    ]
